name: Build and Run .NET 6 Hello World

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Also triggers on PRs to the main branch

jobs:
  build:
    runs-on: windows-latest  # You can change this to windows-latest or macos-latest if needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # This step checks out the code in the repository

    - name: Check .NET Version
      run: "Get-ChildItem env:Path | Format-List *"
       
   # - name: Check .NET Version
   #   run: 'C:\Program Files\dotnet\dotnet.exe --version'

   # - name: Check .NET Version
   #   run: |
    #     "C:\Program Files\dotnet\dotnet --version"

    - name: Check .NET Version 1 ls
      run: |
         ls "C:\Program Files\dotnet\"

    - name: Check .NET Version 2 ls
      run: |
         ls "C:\Users\runneradmin\.dotnet\tools\"
       
    - name: Set up .NET 6 SDK
      uses: actions/setup-dotnet@v3  # This action sets up .NET 6 SDK on the runner ok
      with:
        dotnet-version: '6.0'  # Specify the .NET version to use

    #- name: Restore dependencies
     # run: dotnet restore  # Restore the project dependencies

   # - name: Print Dot net Version Details
   #   run: C:\Program Files\dotnet --version

   # - name: Print Path Details
   #   run: "${PATH}"

    - name: Check .NET Version new added
      run: |
        & "C:\Program Files\dotnet\dotnet" --version

    - name: Print few values
      run: |
        & dotnet --list-sdks |
          dotnet --list-runtimes |
          Get-ChildItem -Path C:\ -Filter "global.json" |
          Get-ChildItem -Path D:\ -Filter "global.json"

    #- name: Build the application
     # run: dotnet build ./.github/HelloWorldApp/HelloWorldApp.csproj /v:diag # Build the application in Release configuration

    #- name: Run the application
    #  run: dotnet run --project ./.github/HelloWorldApp/HelloWorldApp.csproj  # Run the application
      

